# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Sungwoo"
description: > # this means to ignore newlines until "email:"
   Robotics Software Engineer - Sungwoo (Jonathan) Kim

email: tobezer@gmail.com
#blog logo
logo: "/assets/images/Profile_pic.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Sungwoo Kim'
author: 'Sungwoo Kim'
author_image: "/assets/images/Profile_pic.jpg"

paginate:	5

url: "https://jonsungwoo.github.io/jon-blog" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: ''

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
#   - icon:	twitter
#     url:	https://twitter.com/dirkfabisch
#     desc: Follow me on twitter
#     share_url: http://twitter.com/share
#     share_title: ?text=
#     share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/jonsungwoo
    desc:	go to github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:


